owner: IOIT-ACM
repo: status

sites:
  - name: IOIT ACM Official Website
    url: https://ioit.acm.org
  - name: IOIT TENET Official Website
    url: https://ioittenet.com
  - name: IOIT MUN Official Website
    url: https://mun.ioittenet.com
  - name: IOIT ACM Link Shortener
    url: https://links.ioit.acm.org
  - name: IOIT ACM ChapterOS
    url: https://os.ioit.acm.org
  - name: IOIT ACM Hackathon
    url: https://hack.ioittenet.com
  - name: IOIT ACM Youth Parliament 
    url: https://yp.ioit.acm.org

status-website:
  cname: status.ioit.acm.org
  logoUrl: https://avatars.githubusercontent.com/u/217227793?v=4
  name: IOIT ACM Status
  introTitle: "**IOIT ACM Status** - real-time uptime monitoring for our websites and services."
  introMessage: This page tracks the live status and uptime history of IOIT ACM's websites and services. Found an issue? [Open one on GitHub](https://github.com/$OWNER/$REPO/issues/new).
  theme: light
  navbar:
    - title: Status
      href: /
    - title: IOIT ACM
      href: https://ioit.acm.org
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
